plugins:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 3
RSpec/NamedSubject:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/SubjectStub:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
